kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=ttyS0"
init:
- linuxkit/init:a68f9fa0c1d9dbfc9c23663749a0b7ac510cbe1c
- linuxkit/runc:v0.8
- linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f
- linuxkit/ca-certificates:v0.8
onboot:
- name: sysctl
  image: linuxkit/sysctl:v0.8
- name: sysfs
  image: linuxkit/sysfs:v0.8
- name: dhcpcd
  image: linuxkit/dhcpcd:v0.8
  command:
  - '/sbin/dhcpcd'
  - '--nobackground'
  - '-f'
  - '/dhcpcd.conf'
  - '-1'
- name: metadata
  image: linuxkit/metadata:v0.8
- name: format
  image: linuxkit/format:v0.8
- name: mount
  image: linuxkit/mount:v0.8
  command:
  - '/usr/bin/mountie'
  - '/var/lib/docker'
services:
- name: rngd
  image: linuxkit/rngd:v0.8
- name: sshd
  image: linuxkit/sshd:666b4a1a323140aa1f332826164afba506abf597
  binds:
  - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  - /etc/resolv.conf:/etc/resolv.conf
  - /run:/run
  - /tmp:/tmp
  - /etc:/hostroot/etc
  - /usr/bin/ctr:/usr/bin/ctr
  - /usr/bin/runc:/usr/bin/runc
  - /containers:/containers
  - /var/log:/var/log
  - /var/lib/containerd:/var/lib/containerd
  - /dev:/dev
  - /sys:/sys
  capabilities:
  - all
- name: ntpd
  image: linuxkit/openntpd:v0.8
- name: docker
  image: docker:19.03.8-dind
  capabilities:
  - all
  net: host
  mounts:
  - type: cgroup
    options:
    - rw
    - nosuid
    - noexec
    - nodev
    - relatime
  binds:
  - /etc/resolv.conf:/etc/resolv.conf
  - /var/lib/docker:/var/lib/docker
  - /lib/modules:/lib/modules
  - /etc/docker/daemon.json:/etc/docker/daemon.json
  - /run/docker:/var/run
  command:
  - /usr/local/bin/docker-init
  - /usr/local/bin/dockerd
  runtime:
    mkdir:
    - /run/docker
- name: compose
  image: containerskit/compose:1.0.0
  binds:
  - /run/docker:/var/run
  - /etc/resolv.conf:/etc/resolv.conf
  - /run/config/userdata:/opt/docker-compose.yml
  command:
  - docker-entrypoint.sh
  - -f
  - /opt/docker-compose.yml
  - up
  runtime:
    mkdir:
    - /run/docker
files:
- path: var/lib/docker
  directory: true
- path: etc/docker/daemon.json
  contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
